"""This file was generated by xsdata, v24.7, on 2024-09-03 08:42:01

Generator: DataclassGenerator
See: https://xsdata.readthedocs.io/
"""

from dataclasses import dataclass, field
from typing import Optional

from xsdata.models.datatype import XmlPeriod

from .ntm_4_av_efi import (
    AlternateIdentifierData,
    ContributorsType,
    CreatorsType,
    DescriptionsData,
    GenreType,
    IwfClassificationCodeType,
    KeywordsType,
    LinksData,
    ProducersType,
    PublishersType,
    ResourceTypeData,
    RightsType,
    SeriesType,
    SubjectAreasType,
    SubjectsData,
    TitlesData,
)

__NAMESPACE__ = (
    "http://www.tib.eu/fileadmin/extern/knm/NTM_4_AV-EFI_Schema.xsd"
)


@dataclass
class Resource:
    class Meta:
        name = "resource"
        namespace = (
            "http://www.tib.eu/fileadmin/extern/knm/NTM_4_AV-EFI_Schema.xsd"
        )

    identifier: Optional[int] = field(
        default=None,
        metadata={
            "type": "Element",
            "required": True,
        },
    )
    creators: Optional[CreatorsType] = field(
        default=None,
        metadata={
            "type": "Element",
            "required": True,
        },
    )
    titles: Optional[TitlesData] = field(
        default=None,
        metadata={
            "type": "Element",
            "required": True,
        },
    )
    publishers: Optional[PublishersType] = field(
        default=None,
        metadata={
            "type": "Element",
            "required": True,
        },
    )
    publication_year: Optional[XmlPeriod] = field(
        default=None,
        metadata={
            "name": "publicationYear",
            "type": "Element",
            "required": True,
        },
    )
    language: Optional[str] = field(
        default=None,
        metadata={
            "type": "Element",
            "required": True,
            "pattern": r"[a-z]{3}",
        },
    )
    video_subtitle_language: Optional[str] = field(
        default=None,
        metadata={
            "name": "videoSubtitleLanguage",
            "type": "Element",
            "pattern": r"[a-z]{3}",
        },
    )
    contributors: Optional[ContributorsType] = field(
        default=None,
        metadata={
            "type": "Element",
        },
    )
    producers: Optional[ProducersType] = field(
        default=None,
        metadata={
            "type": "Element",
        },
    )
    production_year: Optional[str] = field(
        default=None,
        metadata={
            "name": "productionYear",
            "type": "Element",
            "pattern": r"(\d){4}(/(\d){4})?",
        },
    )
    production_place: Optional[str] = field(
        default=None,
        metadata={
            "name": "productionPlace",
            "type": "Element",
        },
    )
    resource_type: Optional[ResourceTypeData] = field(
        default=None,
        metadata={
            "name": "resourceType",
            "type": "Element",
        },
    )
    genre: Optional[GenreType] = field(
        default=None,
        metadata={
            "type": "Element",
        },
    )
    subject_areas: Optional[SubjectAreasType] = field(
        default=None,
        metadata={
            "name": "subjectAreas",
            "type": "Element",
        },
    )
    keywords: Optional[KeywordsType] = field(
        default=None,
        metadata={
            "type": "Element",
        },
    )
    descriptions: Optional[DescriptionsData] = field(
        default=None,
        metadata={
            "type": "Element",
        },
    )
    subjects: Optional[SubjectsData] = field(
        default=None,
        metadata={
            "type": "Element",
        },
    )
    doi: Optional[str] = field(
        default=None,
        metadata={
            "name": "DOI",
            "type": "Element",
            "pattern": r"10\.\d+/.+",
        },
    )
    alternate_identifiers: Optional[AlternateIdentifierData] = field(
        default=None,
        metadata={
            "name": "alternateIdentifiers",
            "type": "Element",
        },
    )
    series: Optional[SeriesType] = field(
        default=None,
        metadata={
            "type": "Element",
        },
    )
    rights: Optional[RightsType] = field(
        default=None,
        metadata={
            "type": "Element",
        },
    )
    format: Optional[str] = field(
        default=None,
        metadata={
            "type": "Element",
        },
    )
    size: Optional[str] = field(
        default=None,
        metadata={
            "type": "Element",
        },
    )
    duration: Optional[str] = field(
        default=None,
        metadata={
            "type": "Element",
            "pattern": r"[0-9][0-9]:[0-9][0-9]:[0-9][0-9]:[0-9][0-9]",
        },
    )
    iwf_signature: Optional[str] = field(
        default=None,
        metadata={
            "name": "iwfSignature",
            "type": "Element",
        },
    )
    iwf_production_year: Optional[str] = field(
        default=None,
        metadata={
            "name": "iwfProductionYear",
            "type": "Element",
        },
    )
    iwf_publication_year: Optional[str] = field(
        default=None,
        metadata={
            "name": "iwfPublicationYear",
            "type": "Element",
        },
    )
    iwf_technical_data: Optional[str] = field(
        default=None,
        metadata={
            "name": "iwfTechnicalData",
            "type": "Element",
        },
    )
    iwf_classification_codes: Optional[IwfClassificationCodeType] = field(
        default=None,
        metadata={
            "name": "iwfClassificationCodes",
            "type": "Element",
        },
    )
    links: Optional[LinksData] = field(
        default=None,
        metadata={
            "type": "Element",
        },
    )
